In [1]:
import numpy as np
import pandas as pd
import matplotlib as plt
import seaborn as sns
from sklearn import decomposition
from sklearn import preprocessing
from sklearn.decomposition import PCA
from sklearn.preprocessing import StandardScaler

In [2]:
df_dispoalim = pd.read_csv('DisponibiliteAlimentaire_2017.csv') #chargement du fichier 
df_dispoalim #affichage des données contenues du fichier

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole
0,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5511,Production,2511,Blé et produits,2017,2017,Milliers de tonnes,4281.00,S,Données standardisées
1,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5611,Importations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,2302.00,S,Données standardisées
2,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5072,Variation de stock,2511,Blé et produits,2017,2017,Milliers de tonnes,-119.00,S,Données standardisées
3,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5911,Exportations - Quantité,2511,Blé et produits,2017,2017,Milliers de tonnes,0.00,S,Données standardisées
4,FBS,Nouveaux Bilans Alimentaire,2,Afghanistan,5301,Disponibilité intérieure,2511,Blé et produits,2017,2017,Milliers de tonnes,6701.00,S,Données standardisées
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
176595,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,5142,Nourriture,2899,Miscellanees,2017,2017,Milliers de tonnes,19.00,S,Données standardisées
176596,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,645,Disponibilité alimentaire en quantité (kg/pers...,2899,Miscellanees,2017,2017,kg,1.33,Fc,Donnée calculée
176597,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,664,Disponibilité alimentaire (Kcal/personne/jour),2899,Miscellanees,2017,2017,Kcal/personne/jour,1.00,Fc,Donnée calculée
176598,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,674,Disponibilité de protéines en quantité (g/pers...,2899,Miscellanees,2017,2017,g/personne/jour,0.04,Fc,Donnée calculée
176599,FBS,Nouveaux Bilans Alimentaire,181,Zimbabwe,684,Disponibilité de matière grasse en quantité (g...,2899,Miscellanees,2017,2017,g/personne/jour,0.02,Fc,Donnée calculée

In [3]:
df_dispoalim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 176600 entries, 0 to 176599
Data columns (total 14 columns):
 #   Column                  Non-Null Count   Dtype
---  ------                  --------------   -----
 0   Code Domaine            176600 non-null  object
 1   Domaine                 176600 non-null  object
 2   Code zone               176600 non-null  int64
 3   Zone                    176600 non-null  object
 4   Code Élément            176600 non-null  int64
 5   Élément                 176600 non-null  object
 6   Code Produit            176600 non-null  int64
 7   Produit                 176600 non-null  object
 8   Code année              176600 non-null  int64
 9   Année                   176600 non-null  int64
 10  Unité                   176600 non-null  object
 11  Valeur                  176600 non-null  float64
 12  Symbole                 176600 non-null  object
 13  Description du Symbole  176600 non-null  object
dtypes: float64(1), int64(5), object(8)
memory usage: 18.9+ MB

In [4]:
df_population = pd.read_csv('Population_2000_2018.csv') #chargement du fichier 
df_population #affichage des données contenues du fichier

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2000,2000,1000 personnes,20779.953,X,Sources internationales sûres,NaN
1,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2001,2001,1000 personnes,21606.988,X,Sources internationales sûres,NaN
2,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2002,2002,1000 personnes,22600.770,X,Sources internationales sûres,NaN
3,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2003,2003,1000 personnes,23680.871,X,Sources internationales sûres,NaN
4,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2004,2004,1000 personnes,24726.684,X,Sources internationales sûres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4406,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2014,2014,1000 personnes,13586.707,X,Sources internationales sûres,NaN
4407,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2015,2015,1000 personnes,13814.629,X,Sources internationales sûres,NaN
4408,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2016,2016,1000 personnes,14030.331,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN
4410,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2018,2018,1000 personnes,14438.802,X,Sources internationales sûres,NaN

In [5]:
df_population.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4411 entries, 0 to 4410
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            4411 non-null   object
 1   Domaine                 4411 non-null   object
 2   Code zone               4411 non-null   int64
 3   Zone                    4411 non-null   object
 4   Code Élément            4411 non-null   int64
 5   Élément                 4411 non-null   object
 6   Code Produit            4411 non-null   int64
 7   Produit                 4411 non-null   object
 8   Code année              4411 non-null   int64
 9   Année                   4411 non-null   int64
 10  Unité                   4411 non-null   object
 11  Valeur                  4411 non-null   float64
 12  Symbole                 4411 non-null   object
 13  Description du Symbole  4411 non-null   object
 14  Note                    258 non-null    object
dtypes: float64(1), int64(5), object(9)
memory usage: 517.0+ KB

In [6]:
df_indicateurs = pd.read_csv('Indicateurs_2017.csv') #chargement du fichier 
df_indicateurs #affichage des données contenues du fichier

,Code Domaine,Domaine,Code zone (M49),Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
0,FS,Données de la sécurité alimentaire,4,Afghanistan,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2017,2017,I$,2058.40,X,Ciffre de sources internationales,NaN
1,FS,Données de la sécurité alimentaire,4,Afghanistan,6121,Valeur,21033,Valeur des importations alimentaires par rappo...,20162018,2016-2018,%,363.00,E,Valeur estimée,NaN
2,FS,Données de la sécurité alimentaire,4,Afghanistan,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2017,2017,indice,-2.80,X,Ciffre de sources internationales,NaN
3,FS,Données de la sécurité alimentaire,710,Afrique du Sud,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2017,2017,I$,13860.30,X,Ciffre de sources internationales,NaN
4,FS,Données de la sécurité alimentaire,710,Afrique du Sud,6121,Valeur,21033,Valeur des importations alimentaires par rappo...,20162018,2016-2018,%,6.00,E,Valeur estimée,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
583,FS,Données de la sécurité alimentaire,894,Zambie,6121,Valeur,21033,Valeur des importations alimentaires par rappo...,20162018,2016-2018,%,4.00,E,Valeur estimée,NaN
584,FS,Données de la sécurité alimentaire,894,Zambie,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2017,2017,indice,0.15,X,Ciffre de sources internationales,NaN
585,FS,Données de la sécurité alimentaire,716,Zimbabwe,6126,Valeur,22013,"PIB par habitant, ($ PPA internationaux consta...",2017,2017,I$,3795.60,X,Ciffre de sources internationales,NaN
586,FS,Données de la sécurité alimentaire,716,Zimbabwe,6121,Valeur,21033,Valeur des importations alimentaires par rappo...,20162018,2016-2018,%,20.00,E,Valeur estimée,NaN
587,FS,Données de la sécurité alimentaire,716,Zimbabwe,6125,Valeur,21032,Stabilité politique et absence de violence/ter...,2017,2017,indice,-0.71,X,Ciffre de sources internationales,NaN

In [7]:
df_indicateurs.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 588 entries, 0 to 587
Data columns (total 15 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Code Domaine            588 non-null    object
 1   Domaine                 588 non-null    object
 2   Code zone (M49)         588 non-null    int64
 3   Zone                    588 non-null    object
 4   Code Élément            588 non-null    int64
 5   Élément                 588 non-null    object
 6   Code Produit            588 non-null    int64
 7   Produit                 588 non-null    object
 8   Code année              588 non-null    int64
 9   Année                   588 non-null    object
 10  Unité                   588 non-null    object
 11  Valeur                  579 non-null    float64
 12  Symbole                 588 non-null    object
 13  Description du Symbole  588 non-null    object
 14  Note                    0 non-null      float64
dtypes: float64(2), int64(4), object(9)
memory usage: 69.0+ KB

Nettoyage des données

In [8]:
df_dispoalim.drop(['Code Domaine', 'Domaine', 'Code zone', 'Code Élément', 'Code Produit', 'Code année', 'Année', 'Symbole', 'Description du Symbole'], axis=1, inplace=True)
df_dispoalim

,Zone,Élément,Produit,Unité,Valeur
0,Afghanistan,Production,Blé et produits,Milliers de tonnes,4281.00
1,Afghanistan,Importations - Quantité,Blé et produits,Milliers de tonnes,2302.00
2,Afghanistan,Variation de stock,Blé et produits,Milliers de tonnes,-119.00
3,Afghanistan,Exportations - Quantité,Blé et produits,Milliers de tonnes,0.00
4,Afghanistan,Disponibilité intérieure,Blé et produits,Milliers de tonnes,6701.00
...,...,...,...,...,...
176595,Zimbabwe,Nourriture,Miscellanees,Milliers de tonnes,19.00
176596,Zimbabwe,Disponibilité alimentaire en quantité (kg/pers...,Miscellanees,kg,1.33
176597,Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Miscellanees,Kcal/personne/jour,1.00
176598,Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Miscellanees,g/personne/jour,0.04
176599,Zimbabwe,Disponibilité de matière grasse en quantité (g...,Miscellanees,g/personne/jour,0.02

In [9]:
df_dispoalim = df_dispoalim[df_dispoalim['Produit'] == 'Viande de Volailles']
df_dispoalim

,Zone,Élément,Produit,Unité,Valeur
651,Afghanistan,Production,Viande de Volailles,Milliers de tonnes,28.00
652,Afghanistan,Importations - Quantité,Viande de Volailles,Milliers de tonnes,29.00
653,Afghanistan,Variation de stock,Viande de Volailles,Milliers de tonnes,0.00
654,Afghanistan,Disponibilité intérieure,Viande de Volailles,Milliers de tonnes,57.00
655,Afghanistan,Pertes,Viande de Volailles,Milliers de tonnes,2.00
...,...,...,...,...,...
176396,Zimbabwe,Nourriture,Viande de Volailles,Milliers de tonnes,67.00
176397,Zimbabwe,Disponibilité alimentaire en quantité (kg/pers...,Viande de Volailles,kg,4.68
176398,Zimbabwe,Disponibilité alimentaire (Kcal/personne/jour),Viande de Volailles,Kcal/personne/jour,16.00
176399,Zimbabwe,Disponibilité de protéines en quantité (g/pers...,Viande de Volailles,g/personne/jour,1.59
176400,Zimbabwe,Disponibilité de matière grasse en quantité (g...,Viande de Volailles,g/personne/jour,0.99

In [10]:
liste = ('Production', 'Importations - Quantité', 'Variation de stock',
       'Exportations - Quantité', 'Disponibilité intérieure',
       'Aliments pour animaux', 'Semences', 'Pertes',
       'Nourriture',
       'Disponibilité alimentaire en quantité (kg/personne/an)',
       'Disponibilité alimentaire (Kcal/personne/jour)',
       'Disponibilité de protéines en quantité (g/personne/jour)',
       'Traitement', 'Autres utilisations (non alimentaire)')

In [11]:
df_dispoalim = df_dispoalim.loc[df_dispoalim['Élément'].isin(liste),:]

In [12]:
df_dispoalim['Produit'].unique()

array(['Viande de Volailles'], dtype=object)

In [13]:
df_dispoalim.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 1647 entries, 651 to 176399
Data columns (total 5 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   Zone     1647 non-null   object
 1   Élément  1647 non-null   object
 2   Produit  1647 non-null   object
 3   Unité    1647 non-null   object
 4   Valeur   1647 non-null   float64
dtypes: float64(1), object(4)
memory usage: 77.2+ KB

In [14]:
dispopivot = pd.pivot(df_dispoalim, index=['Zone'], columns=['Élément'],values=['Valeur'])
dispopivot

                                     Valeur  \
Élément               Aliments pour animaux
Zone
Afghanistan                             NaN
Afrique du Sud                          NaN
Albanie                                 NaN
Algérie                                 NaN
Allemagne                               NaN
...                                     ...
Émirats arabes unis                     NaN
Équateur                                NaN
États-Unis d'Amérique                   NaN
Éthiopie                                NaN
Îles Salomon                            NaN

                                                             \
Élément               Autres utilisations (non alimentaire)
Zone
Afghanistan                                             NaN
Afrique du Sud                                          NaN
Albanie                                                 NaN
Algérie                                                 NaN
Allemagne                                               NaN
...                                                     ...
Émirats arabes unis                                     NaN
Équateur                                                NaN
États-Unis d'Amérique                                  89.0
Éthiopie                                                NaN
Îles Salomon                                            NaN

                                                                      \
Élément               Disponibilité alimentaire (Kcal/personne/jour)
Zone
Afghanistan                                                      5.0
Afrique du Sud                                                 143.0
Albanie                                                         85.0
Algérie                                                         22.0
Allemagne                                                       71.0
...                                                              ...
Émirats arabes unis                                            147.0
Équateur                                                        83.0
États-Unis d'Amérique                                          219.0
Éthiopie                                                         0.0
Îles Salomon                                                    18.0

                                                                              \
Élément               Disponibilité alimentaire en quantité (kg/personne/an)
Zone
Afghanistan                                                         1.53
Afrique du Sud                                                     35.69
Albanie                                                            16.36
Algérie                                                             6.38
Allemagne                                                          19.47
...                                                                  ...
Émirats arabes unis                                                43.47
Équateur                                                           19.31
États-Unis d'Amérique                                              55.68
Éthiopie                                                            0.13
Îles Salomon                                                        4.45

                                                                                \
Élément               Disponibilité de protéines en quantité (g/personne/jour)
Zone
Afghanistan                                                         0.54
Afrique du Sud                                                     14.11
Albanie                                                             6.26
Algérie                                                             1.97
Allemagne                                                           7.96
...                                                                  ...
Émirats arabes unis                                                14.80
Équateur                                                            6.15
États-Unis d'Amérique                                              19.93
Éthiopie                                                            0.04
Îles Salomon                                                        1.51

                                                                        \
Élément               Disponibilité intérieure Exportations - Quantité
Zone
Afghanistan                               57.0                     NaN
Afrique du Sud                          2118.0                    63.0
Albanie                                   47.0                     0.0
Algérie                                  277.0                     0.0
Allemagne                               1739.0                   646.0
...                                        ...                     ...
Émirats arabes unis                      412.0                    94.0
Équateur                                 341.0                     0.0
États-Unis d'Amérique                  18266.0                  3692.0
Éthiopie                                  14.0                     NaN
Îles Salomon                               3.0                     0.0

                                                                            \
Élément               Importations - Quantité Nourriture Pertes Production
Zone
Afghanistan                              29.0       55.0    2.0       28.0
Afrique du Sud                          514.0     2035.0   83.0     1667.0
Albanie                                  38.0       47.0    NaN       13.0
Algérie                                   2.0      264.0   13.0      275.0
Allemagne                               842.0     1609.0    NaN     1514.0
...                                       ...        ...    ...        ...
Émirats arabes unis                     433.0      412.0    NaN       48.0
Équateur                                  0.0      324.0   17.0      340.0
États-Unis d'Amérique                   123.0    18100.0    NaN    21914.0
Éthiopie                                  1.0       14.0    1.0       14.0
Îles Salomon                              6.0        3.0    NaN        0.0


Élément               Semences Traitement Variation de stock
Zone
Afghanistan                NaN        NaN                0.0
Afrique du Sud             NaN        NaN               -0.0
Albanie                    NaN        NaN                4.0
Algérie                    NaN        NaN                0.0
Allemagne                  NaN      167.0              -29.0
...                        ...        ...                ...
Émirats arabes unis        NaN        NaN              -26.0
Équateur                   NaN        NaN               -1.0
États-Unis d'Amérique      NaN       77.0               80.0
Éthiopie                   NaN        NaN                0.0
Îles Salomon               NaN        NaN                3.0

[172 rows x 14 columns]

In [15]:
dispopivot.isna().sum()

        Élément
Valeur  Aliments pour animaux                                       171
        Autres utilisations (non alimentaire)                       138
        Disponibilité alimentaire (Kcal/personne/jour)                0
        Disponibilité alimentaire en quantité (kg/personne/an)        0
        Disponibilité de protéines en quantité (g/personne/jour)      0
        Disponibilité intérieure                                      2
        Exportations - Quantité                                      37
        Importations - Quantité                                       2
        Nourriture                                                    2
        Pertes                                                      105
        Production                                                    4
        Semences                                                    171
        Traitement                                                  126
        Variation de stock                                            3
dtype: int64

In [16]:
dispopivot.columns = dispopivot.columns.droplevel()
dispopivot

Élément,Aliments pour animaux,Autres utilisations (non alimentaire),Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Pertes,Production,Semences,Traitement,Variation de stock
Zone,,,,,,,,,,,,,,
Afghanistan,NaN,NaN,5.0,1.53,0.54,57.0,NaN,29.0,55.0,2.0,28.0,NaN,NaN,0.0
Afrique du Sud,NaN,NaN,143.0,35.69,14.11,2118.0,63.0,514.0,2035.0,83.0,1667.0,NaN,NaN,-0.0
Albanie,NaN,NaN,85.0,16.36,6.26,47.0,0.0,38.0,47.0,NaN,13.0,NaN,NaN,4.0
Algérie,NaN,NaN,22.0,6.38,1.97,277.0,0.0,2.0,264.0,13.0,275.0,NaN,NaN,0.0
Allemagne,NaN,NaN,71.0,19.47,7.96,1739.0,646.0,842.0,1609.0,NaN,1514.0,NaN,167.0,-29.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
Émirats arabes unis,NaN,NaN,147.0,43.47,14.80,412.0,94.0,433.0,412.0,NaN,48.0,NaN,NaN,-26.0
Équateur,NaN,NaN,83.0,19.31,6.15,341.0,0.0,0.0,324.0,17.0,340.0,NaN,NaN,-1.0
États-Unis d'Amérique,NaN,89.0,219.0,55.68,19.93,18266.0,3692.0,123.0,18100.0,NaN,21914.0,NaN,77.0,80.0
Éthiopie,NaN,NaN,0.0,0.13,0.04,14.0,NaN,1.0,14.0,1.0,14.0,NaN,NaN,0.0
Îles Salomon,NaN,NaN,18.0,4.45,1.51,3.0,0.0,6.0,3.0,NaN,0.0,NaN,NaN,3.0

In [17]:
dispopivot = dispopivot.drop(['Aliments pour animaux','Autres utilisations (non alimentaire)','Semences','Traitement','Pertes'], axis=1)
dispopivot

Élément,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Variation de stock
Zone,,,,,,,,,
Afghanistan,5.0,1.53,0.54,57.0,NaN,29.0,55.0,28.0,0.0
Afrique du Sud,143.0,35.69,14.11,2118.0,63.0,514.0,2035.0,1667.0,-0.0
Albanie,85.0,16.36,6.26,47.0,0.0,38.0,47.0,13.0,4.0
Algérie,22.0,6.38,1.97,277.0,0.0,2.0,264.0,275.0,0.0
Allemagne,71.0,19.47,7.96,1739.0,646.0,842.0,1609.0,1514.0,-29.0
...,...,...,...,...,...,...,...,...,...
Émirats arabes unis,147.0,43.47,14.80,412.0,94.0,433.0,412.0,48.0,-26.0
Équateur,83.0,19.31,6.15,341.0,0.0,0.0,324.0,340.0,-1.0
États-Unis d'Amérique,219.0,55.68,19.93,18266.0,3692.0,123.0,18100.0,21914.0,80.0
Éthiopie,0.0,0.13,0.04,14.0,NaN,1.0,14.0,14.0,0.0
Îles Salomon,18.0,4.45,1.51,3.0,0.0,6.0,3.0,0.0,3.0

In [18]:
dispopivot.isna().sum()

Élément
Disponibilité alimentaire (Kcal/personne/jour)               0
Disponibilité alimentaire en quantité (kg/personne/an)       0
Disponibilité de protéines en quantité (g/personne/jour)     0
Disponibilité intérieure                                     2
Exportations - Quantité                                     37
Importations - Quantité                                      2
Nourriture                                                   2
Production                                                   4
Variation de stock                                           3
dtype: int64

Je vais remplacer les valeurs manquantes de la colonne 'Exportations' en utilisant cette formule:  

Disponibilité Intérieure = (Production + Importations - disponibilité alimentaire(Quantité) + Variation de stock) - Exportations
devient alors:  
**Exportations = (Production + Importations - disponibilité alimentaire(Quantité) + Variation de stock) - Disponibilité Intérieure**

In [19]:
dispopivot['Exportations - Quantité']= dispopivot.apply(lambda x : ((x['Production'] + x['Importations - Quantité'] 
                                                                       - x['Disponibilité alimentaire en quantité (kg/personne/an)'] 
                                                                       + x['Variation de stock']) - x['Disponibilité intérieure']) 
                                                          if pd.isnull(x['Exportations - Quantité']) else x['Exportations - Quantité'], axis=1)

In [20]:
dispopivot.isna().sum()

Élément
Disponibilité alimentaire (Kcal/personne/jour)              0
Disponibilité alimentaire en quantité (kg/personne/an)      0
Disponibilité de protéines en quantité (g/personne/jour)    0
Disponibilité intérieure                                    2
Exportations - Quantité                                     4
Importations - Quantité                                     2
Nourriture                                                  2
Production                                                  4
Variation de stock                                          3
dtype: int64

In [21]:
df_population_2017 = df_population.loc[df_population['Année'] == 2017]
df_population_2017

,Code Domaine,Domaine,Code zone,Zone,Code Élément,Élément,Code Produit,Produit,Code année,Année,Unité,Valeur,Symbole,Description du Symbole,Note
17,OA,Séries temporelles annuelles,2,Afghanistan,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,36296.113,X,Sources internationales sûres,NaN
36,OA,Séries temporelles annuelles,202,Afrique du Sud,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,57009.756,X,Sources internationales sûres,NaN
55,OA,Séries temporelles annuelles,3,Albanie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,2884.169,X,Sources internationales sûres,NaN
74,OA,Séries temporelles annuelles,4,Algérie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,41389.189,X,Sources internationales sûres,NaN
93,OA,Séries temporelles annuelles,79,Allemagne,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,82658.409,X,Sources internationales sûres,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4333,OA,Séries temporelles annuelles,236,Venezuela (République bolivarienne du),511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,29402.484,X,Sources internationales sûres,NaN
4352,OA,Séries temporelles annuelles,237,Viet Nam,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,94600.648,X,Sources internationales sûres,NaN
4371,OA,Séries temporelles annuelles,249,Yémen,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,27834.819,X,Sources internationales sûres,NaN
4390,OA,Séries temporelles annuelles,251,Zambie,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,16853.599,X,Sources internationales sûres,NaN
4409,OA,Séries temporelles annuelles,181,Zimbabwe,511,Population totale,3010,Population-Estimations,2017,2017,1000 personnes,14236.595,X,Sources internationales sûres,NaN

In [22]:
df_population_2017 = df_population_2017.drop(['Code Domaine', 'Domaine', 'Code zone', 'Code Élément', 'Élément','Code Produit', 'Produit','Code année','Année','Unité', 'Symbole','Description du Symbole','Note'], axis=1)
df_population_2017

                                        Zone     Valeur
17                               Afghanistan  36296.113
36                            Afrique du Sud  57009.756
55                                   Albanie   2884.169
74                                   Algérie  41389.189
93                                 Allemagne  82658.409
...                                      ...        ...
4333  Venezuela (République bolivarienne du)  29402.484
4352                                Viet Nam  94600.648
4371                                   Yémen  27834.819
4390                                  Zambie  16853.599
4409                                Zimbabwe  14236.595

[236 rows x 2 columns]

In [23]:
df_population_2017.isna().sum()

Zone      0
Valeur    0
dtype: int64

In [24]:
df_indicateurs.drop(['Code Domaine', 'Domaine', 'Code zone (M49)', 'Élément','Code Élément','Code Produit', 'Code année','Année', 'Unité','Symbole', 'Description du Symbole', 'Note'], axis=1, inplace=True)
df_indicateurs

,Zone,Produit,Valeur
0,Afghanistan,"PIB par habitant, ($ PPA internationaux consta...",2058.40
1,Afghanistan,Valeur des importations alimentaires par rappo...,363.00
2,Afghanistan,Stabilité politique et absence de violence/ter...,-2.80
3,Afrique du Sud,"PIB par habitant, ($ PPA internationaux consta...",13860.30
4,Afrique du Sud,Valeur des importations alimentaires par rappo...,6.00
...,...,...,...
583,Zambie,Valeur des importations alimentaires par rappo...,4.00
584,Zambie,Stabilité politique et absence de violence/ter...,0.15
585,Zimbabwe,"PIB par habitant, ($ PPA internationaux consta...",3795.60
586,Zimbabwe,Valeur des importations alimentaires par rappo...,20.00
587,Zimbabwe,Stabilité politique et absence de violence/ter...,-0.71

In [25]:
df_indicateurs = df_indicateurs.drop(df_indicateurs[df_indicateurs['Produit'] == 'Valeur des importations alimentaires par rapport aux exportations totales de marchandises (%) (moyenne sur 3 ans)'].index)
df_indicateurs

,Zone,Produit,Valeur
0,Afghanistan,"PIB par habitant, ($ PPA internationaux consta...",2058.40
2,Afghanistan,Stabilité politique et absence de violence/ter...,-2.80
3,Afrique du Sud,"PIB par habitant, ($ PPA internationaux consta...",13860.30
5,Afrique du Sud,Stabilité politique et absence de violence/ter...,-0.28
6,Albanie,"PIB par habitant, ($ PPA internationaux consta...",12771.00
...,...,...,...
581,Yémen,Stabilité politique et absence de violence/ter...,-2.94
582,Zambie,"PIB par habitant, ($ PPA internationaux consta...",3485.00
584,Zambie,Stabilité politique et absence de violence/ter...,0.15
585,Zimbabwe,"PIB par habitant, ($ PPA internationaux consta...",3795.60
587,Zimbabwe,Stabilité politique et absence de violence/ter...,-0.71

In [26]:
indicateurspivot = pd.pivot(df_indicateurs, index=['Zone'], columns=['Produit'],values=['Valeur'])
indicateurspivot

                                                                          Valeur  \
Produit               PIB par habitant, ($ PPA internationaux constants de 2017)
Zone
Afghanistan                                                       2058.4
Afrique du Sud                                                   13860.3
Albanie                                                          12771.0
Algérie                                                          11737.4
Allemagne                                                        53071.5
...                                                                  ...
Érythrée                                                             NaN
États-Unis d'Amérique                                            59914.8
Éthiopie                                                          2021.6
Îles Marshall                                                     3711.4
Îles Salomon                                                      2663.5


Produit               Stabilité politique et absence de violence/terrorisme (indice)
Zone
Afghanistan                                                        -2.80
Afrique du Sud                                                     -0.28
Albanie                                                             0.38
Algérie                                                            -0.92
Allemagne                                                           0.59
...                                                                  ...
Érythrée                                                           -0.73
États-Unis d'Amérique                                               0.29
Éthiopie                                                           -1.68
Îles Marshall                                                       0.87
Îles Salomon                                                        0.20

[198 rows x 2 columns]

In [27]:
indicateurspivot.columns = indicateurspivot.columns.droplevel()
indicateurspivot

Produit,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice)
Zone,,
Afghanistan,2058.4,-2.80
Afrique du Sud,13860.3,-0.28
Albanie,12771.0,0.38
Algérie,11737.4,-0.92
Allemagne,53071.5,0.59
...,...,...
Érythrée,NaN,-0.73
États-Unis d'Amérique,59914.8,0.29
Éthiopie,2021.6,-1.68
Îles Marshall,3711.4,0.87
Îles Salomon,2663.5,0.20

In [28]:
indicateurspivot.isna().sum()

Produit
PIB par habitant, ($ PPA internationaux constants de 2017)        11
Stabilité politique et absence de violence/terrorisme (indice)     1
dtype: int64

In [29]:
def doublons(df): 
    print(len(df) - len(df.drop_duplicates()), 'doublons')

for i in [df_dispoalim, df_indicateurs, df_population_2017]:
    doublons(i)

0 doublons
0 doublons
0 doublons

Jointure des tables

In [30]:
df_join = pd.merge(dispopivot, df_population_2017, on='Zone', how='outer')
df_join

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Variation de stock,Valeur
0,Afghanistan,5.0,1.53,0.54,57.0,-1.53,29.0,55.0,28.0,0.0,36296.113
1,Afrique du Sud,143.0,35.69,14.11,2118.0,63.00,514.0,2035.0,1667.0,-0.0,57009.756
2,Albanie,85.0,16.36,6.26,47.0,0.00,38.0,47.0,13.0,4.0,2884.169
3,Algérie,22.0,6.38,1.97,277.0,0.00,2.0,264.0,275.0,0.0,41389.189
4,Allemagne,71.0,19.47,7.96,1739.0,646.00,842.0,1609.0,1514.0,-29.0,82658.409
...,...,...,...,...,...,...,...,...,...,...,...
231,Somalie,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14589.179
232,Soudan du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10910.763
233,Tokélaou,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300
234,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.998
235,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.370

In [31]:
df_join = df_join.rename(columns={'Valeur': 'Population'})

In [32]:
df_final=pd.merge(df_join, indicateurspivot, on='Zone', how='outer')
df_final

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Variation de stock,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice)
0,Afghanistan,5.0,1.53,0.54,57.0,-1.53,29.0,55.0,28.0,0.0,36296.113,2058.4,-2.80
1,Afrique du Sud,143.0,35.69,14.11,2118.0,63.00,514.0,2035.0,1667.0,-0.0,57009.756,13860.3,-0.28
2,Albanie,85.0,16.36,6.26,47.0,0.00,38.0,47.0,13.0,4.0,2884.169,12771.0,0.38
3,Algérie,22.0,6.38,1.97,277.0,0.00,2.0,264.0,275.0,0.0,41389.189,11737.4,-0.92
4,Allemagne,71.0,19.47,7.96,1739.0,646.00,842.0,1609.0,1514.0,-29.0,82658.409,53071.5,0.59
...,...,...,...,...,...,...,...,...,...,...,...,...,...
232,Soudan du Sud,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,10910.763,NaN,-2.45
233,Tokélaou,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.300,NaN,NaN
234,Tonga,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,101.998,6466.3,0.79
235,Tuvalu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11.370,4010.1,1.24
236,Chine,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,14520.8,NaN

In [33]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 237 entries, 0 to 236
Data columns (total 13 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Zone                                                            237 non-null    object
 1   Disponibilité alimentaire (Kcal/personne/jour)                  172 non-null    float64
 2   Disponibilité alimentaire en quantité (kg/personne/an)          172 non-null    float64
 3   Disponibilité de protéines en quantité (g/personne/jour)        172 non-null    float64
 4   Disponibilité intérieure                                        170 non-null    float64
 5   Exportations - Quantité                                         168 non-null    float64
 6   Importations - Quantité                                         170 non-null    float64
 7   Nourriture                                                      170 non-null    float64
 8   Production                                                      168 non-null    float64
 9   Variation de stock                                              169 non-null    float64
 10  Population                                                      236 non-null    float64
 11  PIB par habitant, ($ PPA internationaux constants de 2017)      187 non-null    float64
 12  Stabilité politique et absence de violence/terrorisme (indice)  197 non-null    float64
dtypes: float64(12), object(1)
memory usage: 25.9+ KB

In [34]:
df_final_nan= df_final[df_final.isnull().any(axis=1)]
df_final_nan.head()

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Variation de stock,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice)
33,"Chine, Taiwan Province de",126.0,33.17,11.01,785.0,8.00,161.0,785.0,652.0,20.0,23674.546,NaN,0.86
34,"Chine, continentale",59.0,12.33,3.96,18161.0,576.00,452.0,17518.0,18236.0,-50.0,1421021.791,NaN,NaN
40,Cuba,82.0,23.72,7.12,342.0,-25.72,312.0,269.0,29.0,-1.0,11339.254,NaN,0.65
43,Djibouti,9.0,2.68,0.92,3.0,NaN,3.0,3.0,NaN,0.0,944.099,4905.0,-0.74
92,Maldives,47.0,13.50,4.70,12.0,NaN,12.0,7.0,NaN,0.0,496.402,18057.9,0.23

In [35]:
df_final_nan.to_csv('df_final_nan.csv')

In [36]:
df_final.dropna(inplace = True )

In [37]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 0 to 171
Data columns (total 13 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Zone                                                            159 non-null    object
 1   Disponibilité alimentaire (Kcal/personne/jour)                  159 non-null    float64
 2   Disponibilité alimentaire en quantité (kg/personne/an)          159 non-null    float64
 3   Disponibilité de protéines en quantité (g/personne/jour)        159 non-null    float64
 4   Disponibilité intérieure                                        159 non-null    float64
 5   Exportations - Quantité                                         159 non-null    float64
 6   Importations - Quantité                                         159 non-null    float64
 7   Nourriture                                                      159 non-null    float64
 8   Production                                                      159 non-null    float64
 9   Variation de stock                                              159 non-null    float64
 10  Population                                                      159 non-null    float64
 11  PIB par habitant, ($ PPA internationaux constants de 2017)      159 non-null    float64
 12  Stabilité politique et absence de violence/terrorisme (indice)  159 non-null    float64
dtypes: float64(12), object(1)
memory usage: 17.4+ KB

In [38]:
#nouvelles variables
df_final['Tx dépendance importation'] = df_final['Importations - Quantité'] / (df_final['Production'] + df_final['Importations - Quantité'] - df_final['Exportations - Quantité']) * 100
df_final['Tx d autosuffisance'] = df_final['Production'] / (df_final['Production'] + df_final['Importations - Quantité'] - df_final['Exportations - Quantité']) * 100
df_final

,Zone,Disponibilité alimentaire (Kcal/personne/jour),Disponibilité alimentaire en quantité (kg/personne/an),Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Nourriture,Production,Variation de stock,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice),Tx dépendance importation,Tx d autosuffisance
0,Afghanistan,5.0,1.53,0.54,57.0,-1.53,29.0,55.0,28.0,0.0,36296.113,2058.4,-2.80,49.547241,47.838715
1,Afrique du Sud,143.0,35.69,14.11,2118.0,63.00,514.0,2035.0,1667.0,-0.0,57009.756,13860.3,-0.28,24.268178,78.706327
2,Albanie,85.0,16.36,6.26,47.0,0.00,38.0,47.0,13.0,4.0,2884.169,12771.0,0.38,74.509804,25.490196
3,Algérie,22.0,6.38,1.97,277.0,0.00,2.0,264.0,275.0,0.0,41389.189,11737.4,-0.92,0.722022,99.277978
4,Allemagne,71.0,19.47,7.96,1739.0,646.00,842.0,1609.0,1514.0,-29.0,82658.409,53071.5,0.59,49.239766,88.538012
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
167,Émirats arabes unis,147.0,43.47,14.80,412.0,94.00,433.0,412.0,48.0,-26.0,9487.203,67183.6,0.62,111.886305,12.403101
168,Équateur,83.0,19.31,6.15,341.0,0.00,0.0,324.0,340.0,-1.0,16785.361,11617.9,-0.07,0.000000,100.000000
169,États-Unis d'Amérique,219.0,55.68,19.93,18266.0,3692.00,123.0,18100.0,21914.0,80.0,325084.756,59914.8,0.29,0.670482,119.454892
170,Éthiopie,0.0,0.13,0.04,14.0,0.87,1.0,14.0,14.0,0.0,106399.924,2021.6,-1.68,7.077141,99.079972
171,Îles Salomon,18.0,4.45,1.51,3.0,0.00,6.0,3.0,0.0,3.0,636.039,2663.5,0.20,100.000000,0.000000

In [39]:
df_final=df_final.drop(['Disponibilité alimentaire (Kcal/personne/jour)','Disponibilité alimentaire en quantité (kg/personne/an)', 'Nourriture', 'Production', 'Variation de stock'], axis=1)
df_final

,Zone,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice),Tx dépendance importation,Tx d autosuffisance
0,Afghanistan,0.54,57.0,-1.53,29.0,36296.113,2058.4,-2.80,49.547241,47.838715
1,Afrique du Sud,14.11,2118.0,63.00,514.0,57009.756,13860.3,-0.28,24.268178,78.706327
2,Albanie,6.26,47.0,0.00,38.0,2884.169,12771.0,0.38,74.509804,25.490196
3,Algérie,1.97,277.0,0.00,2.0,41389.189,11737.4,-0.92,0.722022,99.277978
4,Allemagne,7.96,1739.0,646.00,842.0,82658.409,53071.5,0.59,49.239766,88.538012
...,...,...,...,...,...,...,...,...,...,...
167,Émirats arabes unis,14.80,412.0,94.00,433.0,9487.203,67183.6,0.62,111.886305,12.403101
168,Équateur,6.15,341.0,0.00,0.0,16785.361,11617.9,-0.07,0.000000,100.000000
169,États-Unis d'Amérique,19.93,18266.0,3692.00,123.0,325084.756,59914.8,0.29,0.670482,119.454892
170,Éthiopie,0.04,14.0,0.87,1.0,106399.924,2021.6,-1.68,7.077141,99.079972
171,Îles Salomon,1.51,3.0,0.00,6.0,636.039,2663.5,0.20,100.000000,0.000000

In [40]:
df_final.describe()

,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice),Tx dépendance importation,Tx d autosuffisance
count,159.000000,159.000000,159.000000,159.000000,1.590000e+02,159.000000,159.000000,159.000000,159.000000
mean,7.202579,598.264151,107.207107,88.635220,3.621213e+04,20670.869811,-0.044277,47.014246,75.424522
std,5.655099,1776.415889,474.598625,189.337366,1.149884e+05,21028.922553,0.886644,99.235598,51.264089
min,0.040000,2.000000,-70.310000,0.000000,5.204500e+01,912.800000,-2.800000,0.000000,0.000000
25%,2.100000,32.000000,0.000000,3.000000,2.902508e+03,4970.650000,-0.625000,4.013423,41.381988
50%,6.520000,98.000000,1.000000,16.000000,9.487203e+03,13589.700000,0.030000,20.610687,85.523054
75%,10.390000,349.000000,18.500000,80.500000,3.046071e+04,29781.350000,0.670000,68.823964,99.779020
max,27.870000,18266.000000,4223.000000,1069.000000,1.338677e+06,126144.000000,1.600000,1045.751634,379.310345

In [41]:
df_final.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 159 entries, 0 to 171
Data columns (total 10 columns):
 #   Column                                                          Non-Null Count  Dtype
---  ------                                                          --------------  -----
 0   Zone                                                            159 non-null    object
 1   Disponibilité de protéines en quantité (g/personne/jour)        159 non-null    float64
 2   Disponibilité intérieure                                        159 non-null    float64
 3   Exportations - Quantité                                         159 non-null    float64
 4   Importations - Quantité                                         159 non-null    float64
 5   Population                                                      159 non-null    float64
 6   PIB par habitant, ($ PPA internationaux constants de 2017)      159 non-null    float64
 7   Stabilité politique et absence de violence/terrorisme (indice)  159 non-null    float64
 8   Tx dépendance importation                                       159 non-null    float64
 9   Tx d autosuffisance                                             159 non-null    float64
dtypes: float64(9), object(1)
memory usage: 13.7+ KB

In [42]:
#définition de l'index pour utiliser la méthode PCA pour identifier les outliers
df_final.set_index('Zone', inplace = True)

In [82]:
# Sélectionner les colonnes numériques
cols_num = df_final.select_dtypes(include=['float64', 'int64']).columns
df_num = df_final[cols_num]

# Standardiser les données
scaler = StandardScaler()
df_scaled = scaler.fit_transform(df_num)

# Appliquer la méthode PCA
pca = PCA(n_components=9)
pca.fit(df_scaled)
principal_components = pca.transform(df_scaled)

# Identifier les outliers
outliers = df_final.iloc[principal_components[:, 0].argsort()[-3:][::-1]]
outliers

,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice),Tx dépendance importation,Tx d autosuffisance
Zone,,,,,,,,,
Chine - RAS de Hong-Kong,22.26,280.0,663.0,907.0,7306.322,59842.2,0.83,338.432836,8.955224
Allemagne,7.96,1739.0,646.0,842.0,82658.409,53071.5,0.59,49.239766,88.538012
Royaume-Uni de Grande-Bretagne et d'Irlande du Nord,13.77,2234.0,359.0,779.0,66727.461,46372.4,0.39,34.870188,81.199642

In [44]:
#suppression des 3 outliers pour ne pas biaiser notre analyse
# Supprimer les outliers du DataFrame final
df_final = df_final.drop(outliers.index)
df_final.describe()

,Disponibilité de protéines en quantité (g/personne/jour),Disponibilité intérieure,Exportations - Quantité,Importations - Quantité,Population,"PIB par habitant, ($ PPA internationaux constants de 2017)",Stabilité politique et absence de violence/terrorisme (indice),Tx dépendance importation,Tx d autosuffisance
count,156.000000,156.000000,156.000000,156.000000,1.560000e+02,156.000000,156.000000,156.000000,156.000000
mean,7.058462,426.307692,49.441859,85.634615,3.338326e+04,20238.078846,-0.049872,46.569932,72.765727
std,5.573055,777.613750,151.536545,186.381956,1.128690e+05,20802.977352,0.890748,99.193492,45.106849
min,0.040000,2.000000,-70.310000,0.000000,5.204500e+01,912.800000,-2.800000,0.000000,0.000000
25%,1.970000,31.500000,0.000000,3.000000,2.874480e+03,4878.650000,-0.632500,4.573785,37.797619
50%,6.405000,94.000000,1.000000,16.000000,9.439622e+03,13265.700000,0.015000,20.611195,83.660696
75%,10.160000,326.500000,16.117500,78.250000,2.929529e+04,28880.475000,0.660000,68.620562,99.387259
max,27.870000,4556.000000,1025.000000,1069.000000,1.338677e+06,126144.000000,1.600000,1045.751634,319.310345

In [45]:
df_final.to_csv('df_final.csv')